### ISSUE TITLE
Fails for package names with uppercase characters

### ISSUE THREAD

**Issue by sdvg** [sindresorhus/latest-version#10]
Example: [`ngVue`](https://www.npmjs.com/package/ngVue) gets transformed to `ngvue` which doesn't exist.

What's the reason for doing `name.toLowerCase()` in index.js?

**Comment by LitoMore** [comment]
@sdvg NPM modules are no longer allowed to have capital letters in their names.

See: https://github.com/npm/validate-npm-package-name/blob/master/index.js#L67

**Comment by sdvg** [comment]
@LitoMore Thanks, I didn't know this.
But I still think it would be nice if this module worked with all npm packages, even old ones.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/latest-version/pull/17#issuecomment-854140745
