### ISSUE TITLE
Replace `package-json` dependency with simple API call

### ISSUE THREAD

**Issue by fregante** [sindresorhus/latest-version#19]
The registry can be queried directly:

https://registry.npmjs.org/@shinnn%2Feslint-config-node

or even fetch a specific version or tag:

https://registry.npmjs.org/@shinnn%2Feslint-config-node/latest

Ideally with any solution other than `got` it's [a lot](https://npmgraph.js.org/?q=latest-version)

**Comment by sindresorhus** [comment]
It's using `package-json` for a reason. It handles custom registries and authentication.

**Comment by sindresorhus** [comment]
> Ideally with any solution other than got it's a lot

I'm unlikely to switch from Got until [Node.js has built-in Fetch support](https://github.com/nodejs/node/issues/19393). It's easy to say that Got is large, but it's large for a reason. Networking is complex. Got started out as a 50 LOC package.
