### ISSUE TITLE
no "bin" in package.json

### ISSUE THREAD

**Issue by ljharb** [sindresorhus/latest-version#2]
Thus, `which latest-version` doesn't find anything after `npm install -g latest-version`.

**Comment by sindresorhus** [comment]
The CLI was moved into a separate package. This is clearly noted in the commit log.

**Comment by ljharb** [comment]
Ah, thanks. That's unfortunate that there wasn't even a deprecation period where it warned me on the command line, but I'll just switch to the cli package.
