### ISSUE TITLE
Fails for Private Scoped Modules

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/latest-version#3]
Running against a private module, latest-version fails with the following message:

```
{ [GotError: GET https://registry.npmjs.org/@private-scope/module-name/latest response code is 401 (Unauthorized)] nested: null, code: 401 }
```

I'd venture a guess that this is a setback due to using the HTTPS endpoint, rather than the npm module. It's probably fair to declare this module public-scope-support only, but the documentation should be updated at a minimum.

**Comment by sindresorhus** [comment]
That is already supported: https://github.com/sindresorhus/package-json/commit/f7ac25020ad6eaa441c601c969cb5713e8334ce0

I assume you only tried with `update-notifier` which is using an older version.

**Comment by shellscape** [comment]
Indeed, that is a true assumption. Thanks for jumping on the update-notifier fix so quickly.
