### ISSUE TITLE
Reliance on "got" greatly increases package size

### ISSUE THREAD

**Issue by natew** [sindresorhus/latest-version#4]
Just a heads up, played a part in me not using a different package because this one added a lot of time to install.

**Comment by sindresorhus** [comment]
`¯\_(ツ)_/¯`

**Comment by natew** [comment]
"open source is amazing"

"every ticket i open gets closed immediately with an impolite response"

**Comment by sindresorhus** [comment]
> every ticket i open gets closed immediately

Maybe you should stop and think whether there's a reason for that.

## 

I already answered your other issue: https://github.com/yeoman/update-notifier/issues/65
