### ISSUE TITLE
Getting version counts as a download in npm registry

### ISSUE THREAD

**Issue by JasonEtco** [sindresorhus/latest-version#6]
Hello!

There's no way for me to verify this, but I believe that using `latest-version` to get my package's version is being considered a download in the npm registry. I released a new npm package 3 days ago and it is already at around 600 downloads, which makes no sense because a) no one follows me on GitHub, b) I haven't marketed it at all. I'd love to believe that people are just using it, but it seems really unlikely.

I realize it isn't a huge problem, I just think it's a little misleading (both for me, hoping to see accurate numbers and for people considering using it who want to see how many people have adopted the package).

Not even sure if there's anything we can do about it, I don't know enough about how npm tracks downloads.

**Comment by sindresorhus** [comment]
No idea how it works and nothing I can do about if that's how it works. Download numbers are also skewed by npm mirrors downloading all packages.
