### ISSUE TITLE
How can I direct the latest-version to use not npmjs.org as registry?

### ISSUE THREAD

**Issue by smartmouse** [sindresorhus/latest-version#7]
In my environment, I am using a private staging registry. I am making of latest-version to calculate the latest version of all the node modules that are of interest in our staging registry. But it seems that the calculation is based on the modules that we published in npmjs.org and not the staing registry.

**Comment by sindresorhus** [comment]
It respects your .npmrc file, so you could define the registry there.

**Comment by smartmouse** [comment]
Thank you for your prompt reply.
The reason why I ask is - it does not. in my .npmrc, I am pointing to the
the staging registry. It does not pick up the @latest from there.
